name: jsonplaceholder_comments_images
description: flutter rest app base on jsonplaceholder api

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3  <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fpdart: 1.1.0
  intl: 0.18.1
  dio: 5.4.0
  pretty_dio_logger: 1.3.1
  retrofit: 4.0.3
  get_it: 7.6.4
  injectable: 2.3.2
  auto_route: 7.8.4
  flutter_bloc: 8.1.3
  freezed_annotation: 2.4.1
  json_serializable: 6.7.1
  json_annotation: 4.8.1
  equatable: 2.0.5
  infinite_scroll_pagination: 4.0.0
  cached_network_image: 3.3.0
  internet_connection_checker: 1.0.0+1



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  freezed: 2.4.5
  build_runner: 2.4.7
  auto_route_generator: 7.3.2
  injectable_generator: 2.4.1
  retrofit_generator: 8.0.5
  mockito: 5.4.3
  mocktail: 1.0.1
  bloc_test: 9.1.5 



flutter:
  generate: true
  uses-material-design: true


assets:
- assets/test/
