name: jsonplaceholder_comments_images
description: flutter rest app base on jsonplaceholder api

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dartz: 0.10.1
  intl: 0.18.0
  dio: 5.2.0
  pretty_dio_logger: 1.3.1
  retrofit: 4.0.1
  get_it: 7.6.0
  injectable: 2.1.2
  auto_route: 7.4.0
  flutter_bloc: 8.1.3
  freezed_annotation: 2.2.0
  json_serializable: 6.7.0
  json_annotation: 4.8.1
  equatable: 2.0.5




  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  freezed: 2.3.5
  build_runner: 2.4.5
  auto_route_generator: 7.1.1
  injectable_generator: 2.1.6
  retrofit_generator: 7.0.1
  mockito: 5.4.1
  mocktail: 0.3.0



flutter:
  generate: true
  uses-material-design: true
