name: jsonplaceholder_comments_images
description: flutter rest app base on jsonplaceholder api

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dartz: any
  intl: any
  dio: any
  pretty_dio_logger: any
  retrofit: any
  get_it: any
  injectable: any
  auto_route: any
  flutter_bloc: any
  freezed_annotation: any
  json_serializable: any
  json_annotation: any
  equatable: any
  infinite_scroll_pagination: any
  cached_network_image: any
  internet_connection_checker: any



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  freezed: any
  build_runner: any
  auto_route_generator: any
  injectable_generator: any
  retrofit_generator: any
  mockito: any
  mocktail: any



flutter:
  generate: true
  uses-material-design: true
